import os

COCO_TEXT_PROMPT = "person . bicycle . car . motorcycle . airplane . bus . train . truck . boat . traffic light . fire hydrant . stop sign . parking meter . bench . bird . cat . dog . horse . sheep . cow . elephant . bear . zebra . giraffe . backpack . umbrella . handbag . tie . suitcase . frisbee . skis . snowboard . sports ball . kite . baseball bat . baseball glove . skateboard . surfboard . tennis racket . bottle . wine glass . cup . fork . knife . spoon . bowl . banana . apple . sandwich . orange . broccoli . carrot . hot dog . pizza . donut . cake . chair . couch . potted plant . bed . dining table . toilet . tv . laptop . mouse . remote . keyboard . cell phone . microwave . oven . toaster . sink . refrigerator . book . clock . vase . scissors . teddy bear . hair drier . toothbrush ."

coco_classes = ['person',
 'bicycle',
 'car',
 'motorcycle',
 'airplane',
 'bus',
 'train',
 'truck',
 'boat',
 'traffic light',
 'fire hydrant',
 'stop sign',
 'parking meter',
 'bench',
 'bird',
 'cat',
 'dog',
 'horse',
 'sheep',
 'cow',
 'elephant',
 'bear',
 'zebra',
 'giraffe',
 'backpack',
 'umbrella',
 'handbag',
 'tie',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard',
 'surfboard',
 'tennis racket',
 'bottle',
 'wine glass',
 'cup',
 'fork',
 'knife',
 'spoon',
 'bowl',
 'banana',
 'apple',
 'sandwich',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza',
 'donut',
 'cake',
 'chair',
 'couch',
 'potted plant',
 'bed',
 'dining table',
 'toilet',
 'tv',
 'laptop',
 'mouse',
 'remote',
 'keyboard',
 'cell phone',
 'microwave',
 'oven',
 'toaster',
 'sink',
 'refrigerator',
 'book',
 'clock',
 'vase',
 'scissors',
 'teddy bear',
 'hair drier',
 'toothbrush']

coco_classes_grounding_idx = {
    'person': [1],
    'bicycle': [3],
    'car': [5],
    'motorcycle': [7],
    'airplane': [9],
    'bus': [11],
    'train': [13],
    'truck': [15],
    'boat': [17],
    'traffic light': [19, 20],
    'fire hydrant': [22, 23, 24],
    'stop sign': [26, 27],
    'parking meter': [29, 30],
    'bench': [32],
    'bird': [34],
    'cat': [36],
    'dog': [38],
    'horse': [40],
    'sheep': [42],
    'cow': [44],
    'elephant': [46],
    'bear': [48],
    'zebra': [50],
    'giraffe': [52, 53, 54],
    'backpack': [56],
    'umbrella': [58],
    'handbag': [60, 61],
    'tie': [63],
    'suitcase': [65],
    'frisbee': [67, 68, 69],
    'skis': [71, 72],
    'snowboard': [74, 75],
    'sports ball': [77, 78],
    'kite': [80],
    'baseball bat': [82, 83],
    'baseball glove': [85, 86],
    'skateboard': [88, 89],
    'surfboard': [91, 92],
    'tennis racket': [94, 95, 96],
    'bottle': [98],
    'wine glass': [100, 101],
    'cup': [103],
    'fork': [105],
    'knife': [107],
    'spoon': [109],
    'bowl': [111],
    'banana': [113],
    'apple': [115],
    'sandwich': [117],
    'orange': [119],
    'broccoli': [121, 122, 123],
    'carrot': [125],
    'hot dog': [127, 128],
    'pizza': [130],
    'donut': [132, 133],
    'cake': [135],
    'chair': [137],
    'couch': [139],
    'potted plant': [141, 142, 143],
    'bed': [145],
    'dining table': [147, 148],
    'toilet': [150],
    'tv': [152],
    'laptop': [154],
    'mouse': [156],
    'remote': [158],
    'keyboard': [160],
    'cell phone': [162, 163],
    'microwave': [165],
    'oven': [167],
    'toaster': [169, 170],
    'sink': [172],
    'refrigerator': [174],
    'book': [176],
    'clock': [178],
    'vase': [180],
    'scissors': [182],
    'teddy bear': [184, 185],
    'hair drier': [187, 188, 189],
    'toothbrush': [191, 192]}

def mkdir(name):
    '''
    Create folder
    '''
    isExists=os.path.exists(name)
    if not isExists:
        try:
            os.makedirs(name)
        except:
            print("already exist")
    return 0
